[package]
name = "dab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
csv = "1.3.0"
serde = { version = "1.0.197", features = ["serde_derive"] }
thiserror = "1.0.57"
